name: Deploy Lambda Function
on: push

jobs:


  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi 
      - name: Zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          
  upload:
      runs-on: ubuntu-latest
      needs: build
      steps: 
        - name: Download Artifact
          uses: actions/download-artifact@v2
          with:
           name: zipped-bundle
        -  name: Configure AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id: ${{ secrets.aws-access-key }}
             aws-secret-access-key: ${{ secrets.aws-secret-key }}
             aws-region: us-east-1
        -   name: Uplaod to S3
            run:  aws s3 cp  ${{ github.sha }}.zip s3://hellogithubactions/${{ github.sha }}.zip
          
         
        
