name: Deploy to Lambda Function
on: 
  push:
   branches:
     - main 
  
 

jobs:

  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install linting libraries
        run: |
            cd function
            pip install flake8
      - name: Lint with flake8
        run: |
            # Select identifies which errors should cause the job to fail
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # The exit zero flag will show errors as warnings and not fail the run
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
             cd function
             python -m pip install --upgrade pip
             if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi 
      - name: Zip bundle
        run: |
            cd function
            zip -r ../python-libraries.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: python-libraries.zip
          
  upload:
      runs-on: ubuntu-latest
      needs: build
      steps: 
        - name: Download Artifact
          uses: actions/download-artifact@v2
          with:
           name: zipped-bundle
        -  name: Configure AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
             aws-region: us-east-1
        -   name: Uplaod to S3
            run:  aws s3 cp  python-libraries.zip s3://hellogithubactions/python-libraries.zip
            
            
  
  test:
    runs-on: ubutnu-latest
    needs: upload
    steps:
     -  name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
             aws-region: us-east-1
     -  name: Create a test function
        run: |
              aws lambda create-function --function-name hellogithubactionslambdatestfunction --code S3Bucket=hellogithubactions,S3Key=python-libraries.zip --handler lambda_function.lambda_handler --runtime python3.8 
     -  name: Wait 30 Seconds
        run: sleep 30
     -  name: Destroy test function
        if:  ${{ always() }}
        run: aws lambda delete-function --function-name hellogithubactionslambdatestfunction       
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
        -  name: Configure AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
             aws-region: us-east-1
        -  name: Update function Code
           run: |
               aws lambda update-function-code --function-name hellogithubactionslambda --s3-bucket hellogithubactions --s3-key python-libraries.zip --publish
             
          
    
          
         
        
